(()=>{
'use strict';
const WEBHOOK_URL='https://n8n.xn----8sbalgvaeklgsbf4b.xn--p1ai/webhook/5ccfbe41-c897-4034-9b75-e986bb9d0fe0/chat';
const SESSION_KEY='vishtynets_ai_session';
function init(){
 const screen=document.querySelector('.screen-ai');if(!screen||screen.dataset.aiInitialized==='1')return;const card=screen.querySelector('.ai-card');if(!card)return;screen.dataset.aiInitialized='1';card.hidden=false;card.innerHTML='';
 const header=document.createElement('header');header.className='ai-header';header.innerHTML='<div class="ai-header-copy"><div class="ai-header-line1"><span class="ai-star">✦</span><span>Музейный помощник</span></div><div class="ai-header-line2">AI-консультант</div></div><button class="ai-close" type="button" aria-label="Закрыть чат">×</button>';screen.querySelector('.section-header')?.remove();screen.insertBefore(header,card);
 const shell=document.createElement('div');shell.className='ai-chat-shell';const messages=document.createElement('div');messages.className='ai-messages';messages.setAttribute('role','log');messages.setAttribute('aria-live','polite');const prompts=document.createElement('div');prompts.className='ai-prompts';const form=document.createElement('form');form.className='ai-input';form.setAttribute('autocomplete','off');form.setAttribute('novalidate','');form.innerHTML='<textarea id="museumAiMessage" name="chat_message" inputmode="text" enterkeyhint="send" autocomplete="off" autocapitalize="sentences" autocorrect="on" spellcheck="true" maxlength="1000" rows="1" placeholder="Задайте вопрос…" aria-label="Вопрос AI-консультанту"></textarea><button type="submit" aria-label="Отправить">→</button>';shell.append(messages,prompts,form);card.append(shell);
 const input=form.querySelector('textarea'),submit=form.querySelector('button');input.setAttribute('data-lpignore','true');input.setAttribute('data-1p-ignore','true');input.setAttribute('data-bwignore','true');input.setAttribute('data-form-type','other');input.setAttribute('role','textbox');let busy=false;
 const getSessionId=()=>{let id=sessionStorage.getItem(SESSION_KEY);if(!id){id=(crypto?.randomUUID?.()||`ai-${Date.now()}-${Math.random().toString(36).slice(2)}`);sessionStorage.setItem(SESSION_KEY,id)}return id};
 const scrollToBottom=()=>requestAnimationFrame(()=>{messages.scrollTop=messages.scrollHeight});const addMessage=(role,text)=>{const item=document.createElement('div');item.className=`ai-message ai-message-${role}`;item.textContent=text;messages.append(item);scrollToBottom();return item};
 addMessage('assistant','Спросите о Роминтской пуще. Помощник поможет найти места, статьи и маршруты.');
 async function sendToAssistant(message,sessionId){const response=await fetch(WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({action:'sendMessage',chatInput:message,sessionId})});if(!response.ok)throw new Error(`HTTP ${response.status}`);const raw=await response.text();let data;try{data=JSON.parse(raw)}catch(e){let output='';for(const line of raw.split(/\n+/)){try{const j=JSON.parse(line);if(j.content)output+=j.content;else if(j.output)output+=j.output}catch(_){} }if(output.trim())return output.trim();throw new Error('Ответ не JSON')}const output=(typeof data?.output==='string'?data.output:typeof data?.text==='string'?data.text:typeof data?.response==='string'?data.response:Array.isArray(data)?data[0]?.output:'')||'';if(!output.trim())throw new Error('В ответе n8n нет текста');return output.trim()}
 const ask=async message=>{message=String(message||'').trim();if(!message||busy)return;busy=true;submit.disabled=true;addMessage('user',message);const typing=addMessage('assistant','Печатает…');try{typing.textContent=await sendToAssistant(message,getSessionId())}catch(error){console.error('Museum AI error',error);typing.textContent=`Не удалось получить ответ. ${error?.message||'Ошибка соединения.'}`}finally{busy=false;submit.disabled=false;input.disabled=false;scrollToBottom()}};
 const promptList=['Что посмотреть рядом с музеем?','Расскажите о Роминтской пуще','Какие есть интересные маршруты?','Что есть в музейных статьях?'];prompts.innerHTML=promptList.map(p=>`<button type="button">${p}</button>`).join('');prompts.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>ask(b.textContent)));form.addEventListener('submit',e=>{e.preventDefault();const message=input.value;input.value='';input.blur();ask(message)});
 header.querySelector('.ai-close').addEventListener('click',()=>{input.blur();screen.classList.remove('is-active');const home=document.querySelector('.bottom-nav [data-nav="home"], [data-nav="home"]');if(home)home.click();else{document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('is-active',s.dataset.screen==='home'));window.scrollTo(0,0)}});
 if(window.visualViewport){const vv=window.visualViewport;const sync=()=>{if(screen.classList.contains('is-active'))screen.style.setProperty('--ai-vh',`${vv.height}px`)};vv.addEventListener('resize',sync);sync()}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();