// Verified boulder points recovered from the legacy Google My Maps source.
// This file extends the existing MUSEUM_POINTS dataset; it does not replace it.
(function(){
  'use strict';
  const points=window.MUSEUM_POINTS=window.MUSEUM_POINTS||[];
  const add=(point)=>{
    if(!points.some(p=>p.id===point.id)) points.push(point);
  };

  add({id:'poi_boulder_giant',slug:'giant-boulder',name:'Памятник природы «Гигантский валун»',category:'Валуны',categories:['Природа','Валуны','Памятники природы'],lat:54.42277,lng:22.55777,address:'750 м восточнее горы Дозор',shortDescription:'Самый крупный валун Калининградской области; гранит серый, окружность около 16,8 м, высота более 2,5 м.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_jagdbude',slug:'boulder-near-jagdbude',name:'Валун вблизи Ягдбуде',category:'Валуны',categories:['Природа','Валуны'],lat:54.395,lng:22.45388,address:'Дорога от пос. Дмитриевка к бывшему н.п. Ягдбуде',shortDescription:'Крупный крупнозернистый розово-серый гранитный валун; обхват 8,07 м, высота 2,05 м.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_belinskoye',slug:'boulder-road-to-belinskoye',name:'Валун по дороге на Белинское',category:'Валуны',categories:['Природа','Валуны'],lat:54.37138,lng:22.30027,address:'Около 800 м от поворота на Белинское',shortDescription:'Гнейсовый валун с красной кварц-полевошпатовой жилой; ширина видимой части скола около 4 м, высота 2,5 м.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_fossa',slug:'boulder-fossa-clearing',name:'Валун у просеки Фосса',category:'Валуны',categories:['Природа','Валуны'],lat:54.37211,lng:22.43751,address:'Просека Фосса',shortDescription:'Крупнозернистый красный гранит; периметр видимой части около 7 м, высота 0,5 м.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_kamennaya_gorka',slug:'boulder-kamennaya-gorka',name:'Валун на Каменной горке',category:'Валуны',categories:['Природа','Валуны'],lat:54.42694,lng:22.55361,address:'Район горы Дозор',shortDescription:'Розовый крупнозернистый гранитный валун около вершины холма «Каменная горка»; обхват 7 м, высота 1,25 м.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_kamennaya_gorka_area',slug:'boulder-near-kamennaya-gorka',name:'Валун в окрестностях Каменной горки',category:'Валуны',categories:['Природа','Валуны'],lat:54.42666,lng:22.55472,address:'Район горы Дозор',shortDescription:'Крупный фрагмент красного гранита; сохранились два фрагмента расколотого валуна.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_lost_jagdbude',slug:'lost-nature-monument-jagdbude',name:'Утерянный памятник природы у дороги от Дмитриевки к Ягдбуде',category:'Валуны',categories:['История','Валуны','Памятники природы'],lat:54.39666,lng:22.45277,address:'Около 1,5 км северо-западнее бывшего н.п. Ягдбуде',shortDescription:'Исторический памятник природы, который не сохранился; на месте находятся шесть каменных столбов.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'historical_lost'});
  add({id:'poi_boulder_krasnolesye_south',slug:'boulder-south-krasnolesye',name:'Валун на южной окраине посёлка Краснолесье',category:'Валуны',categories:['Природа','Валуны','Краснолесье'],lat:54.38815,lng:22.37192,address:'Старый карьер, южная окраина Краснолесья',shortDescription:'Серый гранитный валун; обхват 5,4 м, высота 0,75 м. Объект познавательной программы «Виштынецкие сокровища гномов».',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_belyi',slug:'white-boulder',name:'Валун «Белый»',category:'Валуны',categories:['Природа','Валуны','Памятники природы'],lat:54.38972,lng:22.52138,address:'Около 4 км южнее озера Мариново, дорога к Радужному',shortDescription:'Известный валун Красного леса из серого крупнозернистого гранита; обхват 11,85 м, высота 2,5 м.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_devils',slug:'devils-boulder',name:'Валун «Чёртов камень»',category:'Валуны',categories:['Природа','Валуны','Легенды'],lat:54.40555,lng:22.39277,address:'Около 2 км севернее пос. Сосновка, левый склон долины реки Красной',shortDescription:'Розовый крупнозернистый гранитный валун; обхват 9,85 м, высота 0,7–1 м. На карте 1941 года отмечен как памятник природы.',articleIds:['rominta-legends'],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active'});
  add({id:'poi_boulder_breiter_stein',slug:'breiter-stein',name:'Валун «Широкий камень»',category:'Валуны',categories:['История','Валуны','Памятники природы'],lat:54.35675,lng:22.50317,address:'Около 500 м юго-западнее озера Утиного, за инженерно-техническими сооружениями границы',shortDescription:'Исторический Breiter Stein: серый гранит, диаметр около 4 м, высота 1,5 м. В настоящее время недоступен для посещения.',articleIds:[],photos:[],photoCredits:[],sourceUrls:['https://www.google.com/maps/d/u/0/viewer?hl=ru&ll=54.356755%2C22.503179000000003&z=13&mid=10pcjwH-4wl6fJo-Ocn9RXQnanoVhMCeq'],coordinateStatus:'verified_legacy_user_supplied',status:'active_restricted'});
})();
